# Generated by Django 4.1.2 on 2022-10-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wanted", "0002_alter_application_date_alter_company_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="application",
            name="notice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application",
                to="wanted.company",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application",
                to="wanted.user",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="notice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notice",
                to="wanted.company",
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
