# Generated by Django 4.1.2 on 2022-10-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wanted", "0003_alter_application_id_alter_application_notice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="notice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wanted.notice"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wanted.user"
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wanted.company"
            ),
        ),
    ]
