# Generated by Django 4.1.2 on 2022-10-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wanted", "0004_alter_application_notice_alter_application_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
